# Funding & Support

# The best way to support this project is by subscribing to mySites.guru!
#
# mySites.guru provides professional Joomla site management with:
# - Unlimited sites on one subscription
# - Automated health monitoring (powered by this extension!)
# - One-click updates for Joomla core and extensions
# - Automated backups with offsite storage
# - Security scanning and malware detection
# - Performance monitoring and optimization
# - 24/7 uptime monitoring
# - Expert support from Joomla professionals
#
# Your subscription directly funds the development and maintenance of
# Health Checker for Joomla and other open-source tools for the community.
#
# Learn more: https://mysites.guru

custom: ["https://mysites.guru/pricing", "https://mysites.guru"]
